Repository Tech-Phantoms/community, pull requests merged in 2021-10, with the labels that each got.

#59 new banner added to assets
  README.md
  assets/banner.png
  assets/banner1.png
  assets/logo-1500px.png
  assets/logo-750px.png
Labels: type: feature

#62 docs(readme): adding inital readme
  README.md
Labels: type: docs

#65 fix: banner link in the `README.md` file
  README.md
Labels: type: fix

#63 feat: Add the `Approved label` workflow
  .github/workflows/approved-label.yml
Labels: type: feature
