Repository Tech-Phantoms/community, pull requests merged in 2021-11, with the labels that each got.

#66 docs: improve text in the `README.md` file
  README.md
Labels: type: docs

#95 Improve the `README.md` file
  README.md
Labels: type: docs, status: approved

#98 feat: Add Instagram and logo badges
  README.md
Labels: type: feature

#102 fix: Update Discord invitation
  .github/ISSUE_TEMPLATE/invitation.yml
Labels: type: fix

#104 feat: Add the Discord badge in the `README.md` file
  README.md
Labels: type: feature
